### ISSUE TITLE
第二期：推荐一篇关于数据响应式系统的文章

### ISSUE THREAD

**Issue by mingtao93** [TalkingData/fsd#4]
文章讲解数据响应式系统及其构建，分步骤实现了 vue2.0的响应式，还有详细的代码示例及注释。
[现代前端科技解析 —— 数据响应式系统](https://www.404forest.com/2017/06/28/modern-web-development-tech-analysis-data-reactivity-system/)

**Comment by bluest-hu** [comment]
@mingtao93 介绍能否再详尽一些，可以增加一些较为主观的内容。
