### ISSUE TITLE
第八期：Frontend Ops概述

### ISSUE THREAD

**Issue by baoqger** [TalkingData/fsd#58]
Frontend Ops是这篇文章作者自己定义的一个概念，业界应该还没有统一这种叫法，不过文章作者的意思是，随着前端项目复杂程度的增加，需要类似于DevOps的工程化能力，来进行持续发布、自动化测试等等流程（本文是英文的材料，暂无译文）。

[Intro to Frontend Ops](https://rupl.github.io/frontend-ops/#/)

**Comment by bluest-hu** [comment]
这我上周推荐过
