### ISSUE TITLE
第八期：karma+webpack搭建vue单元测试环境

### ISSUE THREAD

**Issue by Sorzen** [TalkingData/fsd#60]
[karma+webpack搭建vue单元测试环境](http://www.jianshu.com/p/a515fbbdd1b2)
karma+webpack搭建vue单元测试环境介绍了vue单元测试环境搭建及查看源文件的测试覆盖覆盖率。
[Vue单元测试case写法](http://www.jianshu.com/p/45e8c2b26309)
测试环境搭建完成后，在此基础上vue单元测试思路介绍和case的写法。测试框架使用jasmine。

**Comment by wxnet2013** [comment]
1.
